version: "3.8"

services:

  db:

    image: mysql:8.0

    restart: always

    environment:

      MYSQL_DATABASE: capstone_ecommerce # Ensure this matches your DB name in settings.py

      MYSQL_ROOT_PASSWORD: root

    ports:

      - "3307:3306"

    volumes:

      - db_data:/var/lib/mysql

    healthcheck:

      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

      interval: 20s

      timeout: 5s

      retries: 5

  web:

    build: .

    command: gunicorn --bind 0.0.0.0:8000 ecom_backend.wsgi:application # Make sure this points to your project

    volumes:

      - .:/app

    ports:

      - "8000:8000"

    depends_on:

      db:

        condition: service_healthy

    environment:

      - DB_HOST=db

      - DB_NAME=capstone_ecommerce # Ensure this matches your DB name in settings.py

      - DB_USER=root

      - DB_PASSWORD=root

      - DB_PORT=3306 # Use the default MySQL port inside the container

volumes:

  db_data:


networks:

  app-network:
